### ISSUE TITLE
SET allow_experimental_json_type=1; doesn't work

### ISSUE THREAD

**Issue by kanekv** [caioricciuti/ch-ui#13]
### Environment

Docker

### How did you encounter the bug?

run docker, run command

### What did you expect?

command should succeed

### Actual Result

Error: Syntax error: failed at position 37 ('FORMAT') (line 2, col 1): FORMAT JSON. Expected end of query.

**Comment by caioricciuti** [comment]
Hey, not sure what this does, but I can check if out, another way to see the result of your query is to use the inspector and see the request that goes to your instance, maybe you can share the response, then I can take a look...

**Comment by caioricciuti** [comment]
So I've tested and the response I get It's a success, since ch-ui uses `ag-grid-community` to render the content, the response does not have the format the table expect, this problem should be solved on V2 in which I'm currently working on, I'll check if I can update the current version to make it work too... hopefully you can still use ch-ui. Thanks

**Comment by kanekv** [comment]
thanks @caioricciuti no rush for me wrt this issue. I can wait until v2

**Comment by caioricciuti** [comment]
Solved on V2
<img width="640" alt="Screenshot 2024-09-20 at 10 48 03" src="https://github.com/user-attachments/assets/24b1bd6b-96f7-43aa-a142-2e4819ef0d75">
