### ISSUE TITLE
No .env.example file

### ISSUE THREAD

**Issue by clintonm9** [caioricciuti/ch-ui#2]
### Environment

NPM build

### How did you encounter the bug?

cp .env.example .env

### What did you expect?

and .env file :)

### Actual Result

file missing

**Comment by caioricciuti** [comment]
Hello @clintonm9 , you are completely right I just went through the readme and this step is still there, I'm sorry that it's a simple mistake. To give more context, to set up the credentials I've opted to use env variables on Vite, but since we have the docker image built on top of it this was discarded (otherwise if you want to have multiple connections it would be a pain to re-run the container each time). Looks like I oversaw the readme, I'll update it. You should be able to use the app and build it anyways. Thank you!
