### ISSUE TITLE
Non dockered ch-ui trying to connect CH locally

### ISSUE THREAD

**Issue by ss-smk** [caioricciuti/ch-ui#25]
### Environment

NPM build

### How did you encounter the bug?

1. I installed ch-ui locally, like clickhouse server.
2. I don't want to run them in docker, because it's already running in virtual machine. 
3. When i truing to set "ClickHouse URL": http://localhost:8123 , i see, that my browser making POST request to http://localhost:8123/ on my computer, which didn't have CH, so i got error "Server is not availible". 
When i change ClickHouse URL to "http://127.0.0.1:8123", POST request changed to "POST http://127.0.0.1:8123/". 
![ch-ui](https://github.com/user-attachments/assets/6ee3b6fc-bb27-48d2-86b8-08cf63cfa288)

### What did you expect?

I suppose, that ch-ui must check/connect to clickhouse inside his code, not via my browser, because it's more secure.
Maybe this problem didnt uppear in docker because it already uses external ip's, but ch-ui have non-dockered install method, and it seems broken while it running not on local pc. 

### Actual Result

I suppose, hat ch-ui must communicate with clickhouse himself, without browser connection to CH.

**Comment by caioricciuti** [comment]
Hey @ss-smk this is not a problem of the application... The app itself uses the official `nodejs` web-client of click house... 

The app will connect to the `ip` / `url` you provide, since you're using a VM make sure that you are setting to the VM's IP where click house is running... 

The network requests you're seeing in the browser console are client-side requests, which are different from the actual server-side requests made by the ClickHouse client in the React application. The createClient function in the ClickHouse context is creating a server-side client, which communicates directly with the ClickHouse server without going through the browser...

 When you use "localhost" or "127.0.0.1" in the browser, it's subject to the same-origin policy. The browser treats these as requests to itself, not to the ClickHouse server running on your virtual machine. Since you're running ClickHouse on a virtual machine, you should use the VM's IP address instead of "localhost" or "127.0.0.1" in the ClickHouse URL field. This will ensure that the server-side client connects to the correct address.
 
 ## Possible Solutions: 
 

- Use the VM's IP address in the ClickHouse URL field instead of "localhost" or "127.0.0.1".
- Check your VM's network configuration to ensure it allows incoming connections on the ClickHouse port.
- If you still encounter issues, you may need to configure CORS on the ClickHouse server to allow requests from the app's origin. See issue #8
